"""empty message

Revision ID: 6e5cb6bed6d8
Revises: 
Create Date: 2025-12-05 14:12:02.635770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5cb6bed6d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_elements',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('buisness_elements', sa.Enum('USERS', 'PRODUCTS', 'ORDERS', 'STORES', name='buisnesselements'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'MANAGER', name='role'), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'MANAGER', name='role'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('username')
    )
    op.create_table('access_role_rules',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'MANAGER', name='role'), nullable=False),
    sa.Column('element_id', sa.BIGINT(), nullable=False),
    sa.Column('read_permission', sa.BOOLEAN(), nullable=False),
    sa.Column('read_all_permission', sa.BOOLEAN(), nullable=False),
    sa.Column('create_permission', sa.BOOLEAN(), nullable=False),
    sa.Column('update_permission', sa.BOOLEAN(), nullable=False),
    sa.Column('update_all_permission', sa.BOOLEAN(), nullable=False),
    sa.Column('delete_permission', sa.BOOLEAN(), nullable=False),
    sa.Column('delete_all_permission', sa.BOOLEAN(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['business_elements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('revoked', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('refresh_tokens')
    op.drop_table('access_role_rules')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('business_elements')
    # ### end Alembic commands ###
